import { betterAuth } from 'better-auth'
import { customSession, jwt, magicLink } from 'better-auth/plugins'
import { oauthProvider } from '@better-auth/oauth-provider'
import { adminOids, type Bindings } from './env'
import { getAuthDb } from './auth-db'
import { first, getDb, rows } from './db'
import { sendMagicLinkEmail } from './email'

const WWW_ORIGINS = [
  'https://www.beaglabs.com',
  'https://beaglabs.com',
  'http://localhost:3000',
  'http://127.0.0.1:3000',
] as const

function authErrorDetails(error: unknown): Record<string, unknown> {
  if (error instanceof Error) {
    const cause = (error as Error & { cause?: unknown }).cause
    return {
      name: error.name,
      message: error.message,
      stack: error.stack,
      cause: cause instanceof Error
        ? { name: cause.name, message: cause.message, stack: cause.stack }
        : cause,
      ...Object.fromEntries(Object.entries(error)),
    }
  }

  if (error && typeof error === 'object') {
    return { ...(error as Record<string, unknown>) }
  }

  return { value: String(error) }
}

async function canUsePartnerEmail(env: Bindings, email: string): Promise<boolean> {
  const normalized = email.trim().toLowerCase()
  const row = first<Record<string, unknown>>(await getDb(env).execute({
    sql: `SELECT 1 AS allowed FROM partner_users
          WHERE lower(email)=? AND status='active'
          UNION ALL
          SELECT 1 AS allowed FROM partner_invites
          WHERE lower(email)=? AND status='pending' AND expires_at>?
          LIMIT 1`,
    args: [normalized, normalized, new Date().toISOString()],
  }))
  return Boolean(row)
}

/**
 * Better Auth 1.7 uses Microsoft's immutable Entra `oid` as the provider-side
 * account identifier. Older 1.6 Microsoft account rows used `sub`, and a user can
 * temporarily have both rows while that identity is migrated/re-linked.
 *
 * Never take an arbitrary first Microsoft account row and call it an OID. Resolve
 * only an account identifier that is actually present in the immutable admin OID
 * allowlist. This keeps authorization anchored to Entra `oid` while tolerating a
 * stale pre-1.7 `sub` row in the same Better Auth user.
 *
 * The first query matches Better Auth's generated SQLite/Kysely schema. The
 * camelCase fallback keeps this tolerant of an older local schema generated by
 * a different adapter.
 */
async function microsoftOidForUser(env: Bindings, userId: string): Promise<string> {
  const allowed = adminOids(env)
  if (allowed.size === 0) return ''

  const db = getDb(env)
  const queries = [
    {
      sql: `SELECT account_id AS oid FROM account WHERE user_id=? AND provider_id='microsoft'`,
      args: [userId],
    },
    {
      sql: `SELECT accountId AS oid FROM account WHERE userId=? AND providerId='microsoft'`,
      args: [userId],
    },
  ]

  for (const query of queries) {
    try {
      const result = await db.execute(query)
      for (const row of rows<Record<string, unknown>>(result)) {
        const oid = String(row.oid ?? '').trim().toLowerCase()
        if (oid && allowed.has(oid)) return oid
      }
      // The query succeeded, so this database uses this column convention. Any
      // Microsoft rows it returned were stale/non-admin identifiers, not an OID
      // authorized for licensing administration.
      return ''
    } catch {
      // Try the alternate Better Auth column naming convention.
    }
  }
  return ''
}

export function buildAuth(env: Bindings) {
  const allowed = adminOids(env)
  const tenantId = env.MICROSOFT_TENANT_ID.toLowerCase()

  return betterAuth({
    database: {
      db: getAuthDb(env),
      type: 'sqlite',
      // Turso/libSQL is reached from this Worker over its HTTP/Hrana transport.
      // Better Auth social callbacks otherwise wrap user/account/session creation
      // in an interactive Kysely transaction, which is not reliable on this
      // serverless transport. Run the writes sequentially instead.
      transaction: false,
    },
    baseURL: env.BASE_URL,
    basePath: '/api/auth',
    secret: env.BETTER_AUTH_SECRET,
    trustedOrigins: [env.BASE_URL, ...WWW_ORIGINS],
    onAPIError: {
      onError: (error) => {
        console.error('Better Auth API error', authErrorDetails(error))
      },
    },
    session: {
      expiresIn: 60 * 60 * 8,
      cookieCache: {
        enabled: true,
        maxAge: 60 * 30,
        strategy: 'jwe',
      },
    },
    account: {
      storeStateStrategy: 'cookie',
      accountLinking: {
        enabled: true,
        // Admin Microsoft OAuth is constrained below by both the configured
        // tenant and immutable Entra OID allowlist. Better Auth 1.7 treats a
        // trusted provider as sufficient for implicit same-email linking, so no
        // pre-link mutation of the local user's email verification state is
        // required here.
        trustedProviders: ['microsoft'],
        allowDifferentEmails: false,
      },
    },
    advanced: {
      database: {
        joins: false,
        // Better Auth 1.7 validates Kysely schemas by introspecting the live
        // database at runtime. Turso/libSQL's remote Hrana path can reject that
        // metadata introspection even when ordinary queries are healthy, causing
        // every auth request to fail before session lookup. Migrations and CI
        // remain the source of truth for schema validation.
        validateSchema: false,
      },
    },
    user: {
      additionalFields: {
        // Retained for compatibility with databases already migrated with these
        // columns. Authorization does not trust values stored here; customSession
        // derives them from the Microsoft account relation below.
        entraOid: {
          type: 'string',
          required: false,
          input: false,
          returned: true,
        },
        entraTenantId: {
          type: 'string',
          required: false,
          input: false,
          returned: true,
        },
      },
      validateUserInfo: async ({ source }) => {
        // Magic-link partner accounts are admitted by sendMagicLink below. Any
        // OAuth-created account is reserved for the Beag admin Microsoft tenant.
        if (!source.oauth) return
        if (source.oauth.providerId !== 'microsoft') {
          return {
            error: 'microsoft_required',
            errorDescription: 'Microsoft Entra ID is required for Beag Labs licensing administration.',
          }
        }

        const profile = (source.oauth.profile ?? {}) as Record<string, unknown>
        const oid = String(profile.oid ?? '').toLowerCase()
        const tid = String(profile.tid ?? '').toLowerCase()

        if (!oid || !tid || tid !== tenantId || !allowed.has(oid)) {
          return {
            error: 'admin_not_allowed',
            errorDescription: 'This Microsoft Entra identity is not authorized to administer Beag Labs licensing.',
          }
        }
      },
    },
    socialProviders: {
      microsoft: {
        clientId: env.MICROSOFT_CLIENT_ID,
        clientSecret: env.MICROSOFT_CLIENT_SECRET,
        tenantId: env.MICROSOFT_TENANT_ID,
        authority: 'https://login.microsoftonline.com',
        prompt: 'select_account',
        disableProfilePhoto: true,
        mapProfileToUser: (profile) => {
          const oid = String(profile.oid ?? '')
          const preferred = typeof profile.preferred_username === 'string' ? profile.preferred_username : undefined
          return {
            email: profile.email ?? preferred ?? `${oid || 'unknown'}@entra.invalid`,
          }
        },
      },
    },
    plugins: [
      customSession(async ({ user, session }) => {
        const oid = await microsoftOidForUser(env, user.id)
        return {
          session,
          user: {
            ...user,
            entraOid: oid || undefined,
            entraTenantId: oid ? env.MICROSOFT_TENANT_ID : undefined,
          },
        }
      }),
      jwt(),
      magicLink({
        expiresIn: 15 * 60,
        storeToken: 'hashed',
        sendMagicLink: async ({ email, url }) => {
          if (!(await canUsePartnerEmail(env, email))) {
            throw new Error('partner_not_invited')
          }
          await sendMagicLinkEmail(env, email, url)
        },
      }),
      oauthProvider({
        loginPage: '/partner/login',
        consentPage: '/oauth/consent',
        allowDynamicClientRegistration: false,
        scopes: [
          'openid',
          'profile',
          'email',
          'offline_access',
          'partner:catalog',
          'partner:orders',
        ],
      }),
    ],
  })
}

export type LicenseAuth = ReturnType<typeof buildAuth>
