type Row = Record<string, unknown>

export function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
}

function money(cents: unknown): string {
  if (cents === null || cents === undefined || cents === '') return 'Contact Beag'
  const number = Number(cents)
  if (!Number.isFinite(number)) return '—'
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(number / 100)
}

function revenue(value: unknown): string {
  const number = Number(value)
  if (!Number.isFinite(number)) return '—'
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(number)
}

function date(value: unknown): string {
  if (!value) return '—'
  const parsed = new Date(String(value))
  return Number.isNaN(parsed.valueOf()) ? escapeHtml(value) : parsed.toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })
}

function status(value: unknown): string {
  const text = String(value ?? 'unknown')
  return `<span class="status status-${escapeHtml(text)}">${escapeHtml(text.replaceAll('_', ' '))}</span>`
}

const styles = `
:root{--paper:#fafaf9;--ink:#111;--orange:#ff5f1f;--muted:#666;--green:#b9f6ca;--red:#ffd4d4;--yellow:#fff0a6}
*{box-sizing:border-box}html{background:var(--paper);color:var(--ink)}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--paper);color:var(--ink)}a{color:inherit}
.nav{position:fixed;z-index:50;top:0;left:0;right:0;height:72px;background:#fff;border-bottom:3px solid var(--ink);display:flex;align-items:center;justify-content:space-between;padding:0 28px}.brand{display:flex;align-items:center;gap:11px;font-weight:950;letter-spacing:.08em;text-decoration:none}.brand-mark{width:22px;height:22px;background:var(--orange);border:3px solid var(--ink);box-shadow:3px 3px 0 var(--ink)}.nav-links{display:flex;gap:10px;align-items:center}.nav a.link{font-size:12px;font-weight:900;text-transform:uppercase;text-decoration:none;padding:8px 10px;border:2px solid transparent}.nav a.link:hover{border-color:var(--ink);background:#fff4ee}
main{max-width:1280px;margin:0 auto;padding:118px 28px 76px}.eyebrow{display:inline-block;background:var(--orange);border:2px solid var(--ink);box-shadow:3px 3px 0 var(--ink);padding:5px 10px;font:800 11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em;text-transform:uppercase}.hero{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,.7fr);gap:28px;align-items:start;margin-bottom:34px}.hero h1{font-size:clamp(42px,6vw,78px);line-height:.93;letter-spacing:-.045em;margin:20px 0 16px;max-width:900px}.lede{font-size:18px;line-height:1.55;max-width:780px;color:#333}.rule{border:0;border-top:3px solid var(--ink);margin:34px 0}
.card{border:3px solid var(--ink);background:#fff;box-shadow:6px 6px 0 var(--ink);padding:24px}.card.orange{background:var(--orange)}.card.soft{background:#fff4ee}.card h2,.card h3{margin-top:0}.card + .card{margin-top:20px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:22px}.span-4{grid-column:span 4}.span-5{grid-column:span 5}.span-6{grid-column:span 6}.span-7{grid-column:span 7}.span-8{grid-column:span 8}.span-12{grid-column:span 12}.metric{font-size:36px;font-weight:950;letter-spacing:-.04em;margin:8px 0 2px}.muted{color:var(--muted)}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.small{font-size:12px}.section-title{display:flex;align-items:end;justify-content:space-between;gap:16px;margin:42px 0 16px}.section-title h2{font-size:30px;margin:0;letter-spacing:-.025em}
label{display:block;font:800 11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.1em;margin-bottom:7px}.field{margin-bottom:18px}.input,select,textarea{width:100%;border:2px solid var(--ink);border-radius:0;background:#fff;color:var(--ink);font:600 14px/1.4 Arial,sans-serif;padding:12px 13px;outline:none}.input:focus,select:focus,textarea:focus{box-shadow:4px 4px 0 var(--ink)}textarea{min-height:110px;resize:vertical}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.check-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.check{display:flex;gap:9px;align-items:flex-start;border:2px solid var(--ink);padding:11px;background:#fff}.check input{margin-top:3px;accent-color:var(--orange)}
.btn{appearance:none;border:3px solid var(--ink);border-radius:0;background:#fff;color:var(--ink);font-weight:950;padding:11px 16px;box-shadow:4px 4px 0 var(--ink);cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:8px}.btn:hover{transform:translate(-2px,-2px);box-shadow:6px 6px 0 var(--ink)}.btn:active{transform:translate(2px,2px);box-shadow:2px 2px 0 var(--ink)}.btn.orange{background:var(--orange)}.btn.dark{background:var(--ink);color:#fff}.btn.danger{background:#ff8b8b}.btn.small{padding:7px 10px;border-width:2px;box-shadow:3px 3px 0 var(--ink);font-size:11px}.actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.notice{border:2px solid var(--ink);background:var(--yellow);padding:12px 14px;font-weight:700;margin:14px 0}.notice.ok{background:var(--green)}.notice.error{background:var(--red)}
.table-wrap{overflow:auto;border:3px solid var(--ink);background:#fff;box-shadow:6px 6px 0 var(--ink)}table.data{width:100%;border-collapse:collapse;min-width:760px}table.data th{background:var(--ink);color:#fff;text-align:left;font:800 10px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.09em;text-transform:uppercase;padding:12px}table.data td{padding:13px 12px;border-bottom:2px solid var(--ink);vertical-align:middle;font-size:13px}table.data tr:last-child td{border-bottom:0}.company{display:flex;align-items:center;gap:11px;min-width:210px}.logo{width:40px;height:40px;border:2px solid var(--ink);background:#fff;object-fit:contain;padding:3px}.status{display:inline-block;border:2px solid var(--ink);padding:3px 7px;font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;background:#eee}.status-active,.status-approved,.status-booked,.status-fulfilled{background:var(--green)}.status-pending,.status-draft{background:var(--yellow)}.status-rejected,.status-revoked,.status-cancelled{background:var(--red)}
.steps{counter-reset:steps;display:grid;gap:12px}.step{counter-increment:steps;border:2px solid var(--ink);padding:16px;background:#fff;display:grid;grid-template-columns:42px 1fr;gap:12px}.step:before{content:counter(steps);width:36px;height:36px;background:var(--orange);border:2px solid var(--ink);display:grid;place-items:center;font-weight:950}.step h4{margin:1px 0 5px}.step p{margin:0;color:#444;line-height:1.45}.empty{padding:28px;text-align:center;color:#666}.logo-credit{font-size:11px;color:#666;text-align:right;margin-top:8px}.logo-credit a{font-weight:700}.hide{display:none!important}
footer{max-width:1280px;margin:0 auto;padding:0 28px 50px;color:#666;font-size:12px}
@media(max-width:900px){.hero{grid-template-columns:1fr}.grid{display:block}.grid>.card{margin-bottom:20px}.form-grid,.check-grid{grid-template-columns:1fr}.nav{padding:0 16px}.nav-links .optional{display:none}main{padding:106px 16px 60px}.hero h1{font-size:48px}}
`

function nav(kind: 'public' | 'partner' | 'admin'): string {
  const links = kind === 'admin'
    ? `<a class="link" href="/admin">Admin</a><a class="link optional" href="/partners/apply">Partner application</a>`
    : kind === 'partner'
      ? `<a class="link" href="/portal">Portal</a><a class="link optional" href="#provisioning">Provisioning</a>`
      : `<a class="link" href="/partner/login">Partner sign in</a><a class="link optional" href="/login">Admin</a>`
  return `<nav class="nav"><a class="brand" href="${kind === 'admin' ? '/admin' : kind === 'partner' ? '/portal' : '/partners/apply'}"><span class="brand-mark"></span>BEAG LABS</a><div class="nav-links">${links}</div></nav>`
}

export function page(title: string, body: string, kind: 'public' | 'partner' | 'admin' = 'public', extraScript = ''): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${escapeHtml(title)} · Beag Labs</title><style>${styles}</style></head><body>${nav(kind)}<main>${body}</main><footer>© Beag Labs, Inc. · Secure commercial and provisioning operations.</footer>${extraScript ? `<script>${extraScript}</script>` : ''}</body></html>`
}

export function adminLoginPage(): string {
  return page('Admin sign in', `<div class="hero"><div><span class="eyebrow">Licensing administration</span><h1>Private Beag operations.</h1><p class="lede">Microsoft Entra authentication is required. Only explicitly allowed Beag administrator object IDs can access commercial records or issue Papyrus licenses.</p><div class="actions"><button id="signin" class="btn orange">Sign in with Microsoft</button></div><div id="message"></div></div><div class="card soft"><h3>Admin boundary</h3><p>Partner accounts cannot access this surface. Entitlement activation, deployment registration, license issuance, revocation, and commercial booking stay Beag-controlled.</p></div></div>`, 'public', `
document.getElementById('signin').onclick=async()=>{const m=document.getElementById('message');m.innerHTML='';const r=await fetch('/api/auth/sign-in/social',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:'microsoft',callbackURL:'/admin'})});const b=await r.json().catch(()=>({}));if(r.ok&&b.url){location.assign(b.url)}else{m.innerHTML='<div class="notice error">'+(b.message||b.error||'Unable to start Microsoft sign-in.')+'</div>'}};`)
}

export function partnerApplyPage(products: Row[]): string {
  const skuOptions = products.map((product) => `<label class="check"><input type="checkbox" name="skuInterests" value="${escapeHtml(product.sku)}"><span><strong>${escapeHtml(product.sku)}</strong><br><span class="small muted">${escapeHtml(product.name)} · ${money(product.list_price_cents)}</span></span></label>`).join('')
  return page('Partner application', `<div class="hero"><div><span class="eyebrow">Partner network</span><h1>Work with Beag Labs.</h1><p class="lede">Apply for access to the Beag Labs Partner Portal. Applications are manually reviewed before any account is created. UEI and CAGE are required so we can tie federal channel activity to the correct legal entity.</p></div><div class="card orange"><h3>What access includes</h3><p>Approved partners can view the Papyrus catalog, submit order requests, track order status, and follow provisioning instructions. Partners cannot create entitlements or issue licenses.</p></div></div>
  <div class="grid"><section class="card span-8"><h2>Partner onboarding</h2><p class="muted">All fields below are required unless marked optional.</p><form id="application">
    <div class="form-grid"><div class="field"><label>Company name</label><input class="input" name="companyName" required maxlength="256"></div><div class="field"><label>Company domain</label><input class="input" name="companyDomain" required placeholder="example.com" inputmode="url"></div></div>
    <div class="form-grid"><div class="field"><label>UEI</label><input class="input mono" name="uei" required minlength="12" maxlength="12" pattern="[A-Za-z0-9]{12}" placeholder="12-character UEI"></div><div class="field"><label>CAGE</label><input class="input mono" name="cage" required minlength="5" maxlength="5" pattern="[A-Za-z0-9]{5}" placeholder="5-character CAGE"></div></div>
    <div class="form-grid"><div class="field"><label>Annual revenue (USD)</label><input class="input" type="number" name="annualRevenueUsd" required min="0" step="1" placeholder="25000000"></div><div class="field"><label>Partner type</label><select name="partnerType" required><option value="">Select…</option><option value="distributor">Distributor</option><option value="reseller">Reseller</option><option value="prime">Prime contractor</option><option value="systems_integrator">Systems integrator</option><option value="referral">Referral partner</option><option value="technology">Technology partner</option></select></div></div>
    <div class="form-grid"><div class="field"><label>Main POC name</label><input class="input" name="pocName" required maxlength="200"></div><div class="field"><label>Main POC email</label><input class="input" type="email" name="pocEmail" required></div></div>
    <div class="field"><label>SKUs of interest</label><div class="check-grid">${skuOptions}</div></div>
    <input class="hide" tabindex="-1" autocomplete="off" name="website" aria-hidden="true"><div class="actions"><button class="btn orange" type="submit">Submit for review</button><span class="small muted">Submission does not create an account or contractual commitment.</span></div><div id="message"></div>
  </form></section><aside class="card span-4"><h3>Review process</h3><div class="steps"><div class="step"><div><h4>Submit</h4><p>We record the legal entity, federal identifiers, POC, and product interest.</p></div></div><div class="step"><div><h4>Beag approves</h4><p>Partner Operations receives a one-time approve/reject review email.</p></div></div><div class="step"><div><h4>Register</h4><p>The approved POC receives a single-use invitation to create a passwordless Beag identity.</p></div></div></div></aside></div>`, 'public', `
const form=document.getElementById('application');form.addEventListener('submit',async(e)=>{e.preventDefault();const fd=new FormData(form);const body={companyName:fd.get('companyName'),companyDomain:fd.get('companyDomain'),annualRevenueUsd:Number(fd.get('annualRevenueUsd')),uei:fd.get('uei'),cage:fd.get('cage'),partnerType:fd.get('partnerType'),pocName:fd.get('pocName'),pocEmail:fd.get('pocEmail'),skuInterests:fd.getAll('skuInterests'),website:fd.get('website')};const m=document.getElementById('message');m.innerHTML='<div class="notice">Submitting…</div>';const r=await fetch('/api/partner/applications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(r.ok){form.reset();m.innerHTML='<div class="notice ok">Application submitted. Partner Operations has been notified for review.</div>'}else{m.innerHTML='<div class="notice error">'+(b.message||b.error||'Unable to submit application.')+'</div>'}});`)
}

export function applicationReviewPage(application: Row, token: string, decision: 'approve' | 'reject'): string {
  const skus = Array.isArray(application.skus) ? application.skus : []
  const color = decision === 'approve' ? 'orange' : 'danger'
  return page('Review partner application', `<span class="eyebrow">Email confirmation</span><div class="hero"><div><h1>${decision === 'approve' ? 'Approve' : 'Reject'} ${escapeHtml(application.company_name)}?</h1><p class="lede">This page is intentionally separate from the email link. Opening an email cannot mutate the application; the button below is the explicit confirmation.</p></div></div><div class="grid"><div class="card span-7"><h2>Application</h2><table class="data"><tbody><tr><td><strong>Company</strong></td><td>${escapeHtml(application.company_name)}</td></tr><tr><td><strong>Domain</strong></td><td>${escapeHtml(application.company_domain)}</td></tr><tr><td><strong>UEI</strong></td><td class="mono">${escapeHtml(application.uei)}</td></tr><tr><td><strong>CAGE</strong></td><td class="mono">${escapeHtml(application.cage_code)}</td></tr><tr><td><strong>Annual revenue</strong></td><td>${revenue(application.annual_revenue_usd)}</td></tr><tr><td><strong>Main POC</strong></td><td>${escapeHtml(application.main_poc_name)} · ${escapeHtml(application.main_poc_email)}</td></tr><tr><td><strong>SKUs</strong></td><td>${skus.map(escapeHtml).join(', ')}</td></tr></tbody></table></div><div class="card span-5 ${decision === 'approve' ? 'soft' : ''}"><h2>Confirm decision</h2><p>${decision === 'approve' ? 'Approval creates or links the commercial organization and partner record, then sends the POC a single-use portal invitation.' : 'Rejection closes the application and does not create a partner identity.'}</p><form method="post" action="/partner-application/decision"><input type="hidden" name="token" value="${escapeHtml(token)}"><input type="hidden" name="decision" value="${decision}"><button class="btn ${color}" type="submit">Confirm ${decision}</button></form></div></div>`, 'admin')
}

export function partnerInvitePage(companyName: string, email: string, token: string): string {
  return page('Partner invitation', `<div class="hero"><div><span class="eyebrow">Approved partner</span><h1>Join ${escapeHtml(companyName)} on Beag Labs.</h1><p class="lede">Your company has been approved for partner access. We use a passwordless Beag identity; the secure sign-in link is delivered only to <strong>${escapeHtml(email)}</strong>.</p><div class="actions"><button id="register" class="btn orange">Email my registration link</button></div><div id="message"></div></div><div class="card soft"><h3>Security boundary</h3><p>This invitation grants portal access only. It does not grant entitlement creation, deployment approval, or license issuance rights.</p></div></div>`, 'public', `
document.getElementById('register').onclick=async()=>{const m=document.getElementById('message');m.innerHTML='<div class="notice">Sending secure link…</div>';const r=await fetch('/api/partner/invite/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:${JSON.stringify(token)}})});const b=await r.json().catch(()=>({}));m.innerHTML=r.ok?'<div class="notice ok">Registration link sent. Check ${escapeHtml(email)}.</div>':'<div class="notice error">'+(b.message||b.error||'Unable to send invitation.')+'</div>'};`)
}

export function partnerLoginPage(): string {
  return page('Partner sign in', `<div class="hero"><div><span class="eyebrow">Partner portal</span><h1>Sign in without a password.</h1><p class="lede">Enter an email already associated with an approved Beag Labs partner. We will send a single-use sign-in link.</p><form id="signin" class="card" style="max-width:600px"><div class="field"><label>Partner email</label><input class="input" type="email" name="email" required></div><button class="btn orange">Send sign-in link</button><div id="message"></div></form></div><div class="card"><h3>Not a partner yet?</h3><p>New companies must complete legal-entity onboarding and be approved before sign-in links are issued.</p><a class="btn" href="/partners/apply">Apply to partner</a></div></div>`, 'public', `
document.getElementById('signin').onsubmit=async(e)=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');const m=document.getElementById('message');m.innerHTML='<div class="notice">Sending…</div>';const r=await fetch('/api/auth/sign-in/magic-link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,callbackURL:'/portal',errorCallbackURL:'/partner/login?error=signin'})});m.innerHTML=r.ok?'<div class="notice ok">If that address is authorized, a sign-in link has been sent.</div>':'<div class="notice error">This email is not authorized for partner access.</div>'};`)
}

export function messagePage(title: string, message: string, action?: { label: string; href: string }): string {
  return page(title, `<div class="card" style="max-width:760px;margin:40px auto"><span class="eyebrow">Beag Labs</span><h1 style="font-size:46px;margin-bottom:16px">${escapeHtml(title)}</h1><p class="lede">${escapeHtml(message)}</p>${action ? `<a class="btn orange" href="${escapeHtml(action.href)}">${escapeHtml(action.label)}</a>` : ''}</div>`)
}

export function oauthConsentPage(clientId: string, scope: string, claims: string | null): string {
  const scopes = scope.split(/\s+/).filter(Boolean)
  return page('Authorize application', `<div class="hero"><div><span class="eyebrow">Beag Labs OAuth</span><h1>Authorize application access.</h1><p class="lede">Client <span class="mono">${escapeHtml(clientId)}</span> is requesting access to your approved Beag Labs partner identity.</p></div><div class="card soft"><h3>Requested scopes</h3>${scopes.map((s) => `<div class="check"><strong class="mono">${escapeHtml(s)}</strong></div>`).join('')}</div></div><div class="actions"><button id="allow" class="btn orange">Allow</button><button id="deny" class="btn danger">Deny</button></div><div id="message"></div>`, 'partner', `
async function consent(accept){const m=document.getElementById('message');const body={accept,scope:${JSON.stringify(scope)}};${claims ? `body.claims=${JSON.stringify(claims)};` : ''}const r=await fetch('/api/auth/oauth2/consent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(r.redirected){location.assign(r.url);return}const url=b.url||b.redirectURI||b.redirectUri;if(url){location.assign(url);return}if(r.ok){location.assign('/portal')}else{m.innerHTML='<div class="notice error">'+(b.message||b.error||'Unable to record consent.')+'</div>'}}document.getElementById('allow').onclick=()=>consent(true);document.getElementById('deny').onclick=()=>consent(false);`)
}

export function partnerPortalPage(input: { partner: Row; orders: Row[]; products: Row[]; user: Row }): string {
  const partner = input.partner
  const orders = input.orders
  const catalog = input.products.map((p) => `<tr><td><strong>${escapeHtml(p.sku)}</strong><div class="small muted">${escapeHtml(p.name)}</div></td><td>${money(p.list_price_cents)}</td><td>${escapeHtml(p.term_type)}</td><td>${p.list_price_cents === null ? '<span class="status status-pending">quote</span>' : '<span class="status status-active">priced</span>'}</td></tr>`).join('')
  const orderRows = orders.map((o) => `<tr><td class="mono">${escapeHtml(String(o.id).slice(0, 18))}…</td><td>${date(o.submitted_at)}</td><td>${money(o.total_cents)}</td><td>${Number(o.requires_quote) ? '<span class="status status-pending">quote required</span>' : status(o.status)}</td><td>${escapeHtml(o.end_customer_name || 'Partner / internal')}</td></tr>`).join('')
  const skuOptions = input.products.map((p) => `<option value="${escapeHtml(p.sku)}">${escapeHtml(p.sku)} — ${escapeHtml(p.name)} — ${money(p.list_price_cents)}</option>`).join('')
  return page('Partner portal', `<div class="hero"><div><span class="eyebrow">Partner portal</span><h1>${escapeHtml(partner.legal_name)}</h1><p class="lede">Submit commercial order requests, track Beag review, and follow the provisioning path after an order is booked.</p><div class="actions"><span class="status status-active">approved partner</span><span class="mono small">UEI ${escapeHtml(partner.uei)} · CAGE ${escapeHtml(partner.cage_code)}</span></div></div><div class="card orange"><div class="small mono">SIGNED IN AS</div><h3>${escapeHtml(input.user.email)}</h3><p>${escapeHtml(input.user.role)} · ${escapeHtml(partner.partner_type)}</p><button id="signout" class="btn small">Sign out</button></div></div>
  <div class="section-title"><h2>Catalog</h2><span class="small muted">Partner-visible active SKUs</span></div><div class="table-wrap"><table class="data"><thead><tr><th>SKU</th><th>List price</th><th>Term</th><th>Pricing</th></tr></thead><tbody>${catalog}</tbody></table></div>
  <div class="grid" style="margin-top:34px"><section class="card span-7"><h2>Submit an order request</h2><p class="muted">Submitting creates a draft commercial order for Beag review. Products without a published list price are marked quote-required automatically.</p><form id="order"><div class="field"><label>SKU</label><select name="sku" required><option value="">Select…</option>${skuOptions}</select></div><div class="form-grid"><div class="field"><label>Quantity</label><input class="input" name="quantity" type="number" min="1" max="100" value="1" required></div><div class="field"><label>End customer name (optional)</label><input class="input" name="endCustomerName" placeholder="Agency / company"></div></div><div class="form-grid"><div class="field"><label>End customer UEI (optional)</label><input class="input mono" name="endCustomerUei" maxlength="12"></div><div class="field"><label>End customer CAGE (optional)</label><input class="input mono" name="endCustomerCage" maxlength="5"></div></div><div class="field"><label>Order notes (optional)</label><textarea name="notes" placeholder="Vehicle, contract context, requested start date, mission owner, or other procurement detail."></textarea></div><button class="btn orange" type="submit">Submit order request</button><div id="order-message"></div></form></section>
  <aside class="card span-5" id="provisioning"><h2>Provisioning path</h2><div class="steps"><div class="step"><div><h4>1. Submit</h4><p>Your order enters Beag as a draft. This is not yet a booked contract or entitlement.</p></div></div><div class="step"><div><h4>2. Commercial review</h4><p>Beag confirms pricing, contract/vehicle flow, customer identity, and order details. Quote-required SKUs stay unbooked until price is established.</p></div></div><div class="step"><div><h4>3. Entitlement</h4><p>After Beag marks the order booked or fulfilled, Beag creates the software entitlement for license SKUs.</p></div></div><div class="step"><div><h4>4. Deployment + license</h4><p>The customer provides the Papyrus deployment ID. Beag binds and signs the offline license. Partner users cannot mint or modify licenses.</p></div></div></div></aside></div>
  <div class="section-title"><h2>Your submitted orders</h2></div><div class="table-wrap"><table class="data"><thead><tr><th>Order</th><th>Submitted</th><th>Value</th><th>Status</th><th>End customer</th></tr></thead><tbody>${orderRows || '<tr><td colspan="5" class="empty">No partner orders submitted yet.</td></tr>'}</tbody></table></div>`, 'partner', `
document.getElementById('signout').onclick=async()=>{await fetch('/api/auth/sign-out',{method:'POST'});location.assign('/partner/login')};document.getElementById('order').onsubmit=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const body={sku:f.get('sku'),quantity:Number(f.get('quantity')),endCustomerName:f.get('endCustomerName')||null,endCustomerUei:f.get('endCustomerUei')||null,endCustomerCage:f.get('endCustomerCage')||null,notes:f.get('notes')||null};const m=document.getElementById('order-message');m.innerHTML='<div class="notice">Submitting…</div>';const r=await fetch('/api/partner/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(r.ok){m.innerHTML='<div class="notice ok">Order request submitted'+(b.requiresQuote?' — Beag pricing is required before booking.':'.')+'</div>';setTimeout(()=>location.reload(),900)}else{m.innerHTML='<div class="notice error">'+(b.message||b.error||'Unable to submit order.')+'</div>'}};`)
}

export function adminPortalPage(input: { admin: Row; applications: Row[]; partners: Row[]; orders: Row[]; activity: Row[]; logoToken: string }): string {
  const appRows = input.applications.map((a) => `<tr><td><strong>${escapeHtml(a.company_name)}</strong><div class="small muted">${escapeHtml(a.company_domain)}</div></td><td class="mono">${escapeHtml(a.uei)}<br>${escapeHtml(a.cage_code)}</td><td>${revenue(a.annual_revenue_usd)}</td><td>${escapeHtml(a.main_poc_email)}</td><td>${status(a.status)}</td><td>${date(a.created_at)}</td></tr>`).join('')
  const partnerRows = input.partners.map((p) => { const domain=String(p.domain||''); const logo=domain?`<img class="logo" src="https://img.logo.dev/${encodeURIComponent(domain)}?token=${encodeURIComponent(input.logoToken)}&size=48&format=png&theme=light&retina=true" alt="" loading="lazy">`:`<span class="logo"></span>`; return `<tr><td><div class="company">${logo}<div><strong>${escapeHtml(p.legal_name)}</strong><div class="small muted">${escapeHtml(domain)}</div></div></div></td><td>${escapeHtml(p.partner_type)}</td><td class="mono">${escapeHtml(p.uei)}<br>${escapeHtml(p.cage_code)}</td><td>${escapeHtml(p.poc_email||'—')}</td><td>${status(p.partner_status)}</td><td><button class="btn small invite" data-id="${escapeHtml(p.id)}">Invite POC</button></td></tr>` }).join('')
  const orderRows = input.orders.map((o) => `<tr><td class="mono">${escapeHtml(String(o.id).slice(0,18))}…</td><td>${escapeHtml(o.partner_name)}</td><td>${escapeHtml(o.end_customer_name||'—')}</td><td>${money(o.total_cents)}</td><td>${Number(o.requires_quote)?'<span class="status status-pending">quote required</span>':status(o.status)}</td><td>${date(o.submitted_at)}</td></tr>`).join('')
  const activityRows = input.activity.map((a) => `<tr><td>${date(a.created_at)}</td><td class="mono">${escapeHtml(a.actor_type)}:${escapeHtml(String(a.actor_id).slice(0,18))}</td><td><strong>${escapeHtml(a.action)}</strong></td><td>${escapeHtml(a.resource_type)}</td><td class="mono">${escapeHtml(a.resource_id||'—')}</td></tr>`).join('')
  const pending = input.applications.filter((a)=>a.status==='pending').length
  return page('Admin portal', `<div class="hero"><div><span class="eyebrow">Commercial control plane</span><h1>Partner & provisioning admin.</h1><p class="lede">Review channel activity, active partners, and submitted orders without weakening the Beag-controlled entitlement and license boundary.</p></div><div class="card orange"><div class="small mono">ADMIN</div><h3>${escapeHtml(input.admin.email||input.admin.name||'Beag administrator')}</h3><p>Microsoft Entra verified</p></div></div>
  <div class="grid"><div class="card span-4"><div class="small mono">PENDING APPLICATIONS</div><div class="metric">${pending}</div></div><div class="card span-4"><div class="small mono">ACTIVE PARTNERS</div><div class="metric">${input.partners.length}</div></div><div class="card span-4"><div class="small mono">PARTNER ORDERS</div><div class="metric">${input.orders.length}</div></div></div>
  <div class="section-title"><h2>Partner applications</h2><a class="btn small" href="/partners/apply">Open application form</a></div><div class="table-wrap"><table class="data"><thead><tr><th>Company</th><th>UEI / CAGE</th><th>Revenue</th><th>POC</th><th>Status</th><th>Received</th></tr></thead><tbody>${appRows||'<tr><td colspan="6" class="empty">No applications yet.</td></tr>'}</tbody></table></div>
  <div class="section-title"><h2>Active partners</h2><span class="small muted">Logos resolved by company domain</span></div><div class="table-wrap"><table class="data"><thead><tr><th>Partner</th><th>Type</th><th>UEI / CAGE</th><th>Main POC</th><th>Status</th><th>Access</th></tr></thead><tbody>${partnerRows||'<tr><td colspan="6" class="empty">No active partners.</td></tr>'}</tbody></table></div><div class="logo-credit">Company logos provided by <a href="https://logo.dev" target="_blank" rel="noopener">Logo.dev</a>.</div><div id="invite-message"></div>
  <div class="section-title"><h2>Partner order activity</h2></div><div class="table-wrap"><table class="data"><thead><tr><th>Order</th><th>Partner</th><th>End customer</th><th>Value</th><th>Status</th><th>Submitted</th></tr></thead><tbody>${orderRows||'<tr><td colspan="6" class="empty">No partner-submitted orders.</td></tr>'}</tbody></table></div>
  <div class="section-title"><h2>Audit activity</h2><span class="small muted">Latest 75 recorded mutations</span></div><div class="table-wrap"><table class="data"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>ID</th></tr></thead><tbody>${activityRows||'<tr><td colspan="5" class="empty">No audit events.</td></tr>'}</tbody></table></div>
  <div class="section-title" id="provisioning"><h2>Provisioning controls</h2></div><div class="card soft"><div class="steps"><div class="step"><div><h4>Orders are commercial state</h4><p>Partner submissions remain draft until Beag confirms price and contract flow.</p></div></div><div class="step"><div><h4>Entitlements are explicit</h4><p>Only booked/fulfilled license order items can be converted to entitlements through the admin API.</p></div></div><div class="step"><div><h4>Licenses are deployment-bound</h4><p>Beag registers the deployment and explicitly issues the signed Papyrus license. Partner OAuth scopes do not expose these operations.</p></div></div></div></div>`, 'admin', `
document.querySelectorAll('.invite').forEach(btn=>btn.onclick=async()=>{const m=document.getElementById('invite-message');m.innerHTML='<div class="notice">Sending invite…</div>';const r=await fetch('/api/partner/admin/partners/'+encodeURIComponent(btn.dataset.id)+'/invite',{method:'POST'});const b=await r.json().catch(()=>({}));m.innerHTML=r.ok?'<div class="notice ok">Invitation sent to '+(b.email||'partner POC')+'.</div>':'<div class="notice error">'+(b.message||b.error||'Unable to send invite.')+'</div>'});`)
}
