import type { Recipe } from '../types'

export const skillDistillation: Recipe = {
  id: 'skill-distillation',
  title: 'Skill Distillation',
  part: 'agents',
  order: 5,
  purpose:
    'Compress agentic workflows and decision-making capabilities from large, expensive models (or human demonstrations) into smaller, faster models for efficient deployment.',
  usedBy: ['Small agent models (Phi-3 agents)', 'Tool-use distillation', 'Agent compression'],
  coreIdea:
    'Skill distillation transfers agentic capabilities from a capable but expensive teacher (large LM or human) to a smaller student model. The student learns to imitate the teacher action sequences, tool-use decisions, and planning trajectories. The training data is generated by the teacher executing tasks and logging its full decision process. In addition to action imitation, the student learns the teacher intent — why it chose specific actions — through intermediate reasoning distillation. This enables deployable agents at a fraction of the cost.',
  pipeline: [
    'Select teacher model (capable LM or human demonstrations)',
    'Teacher executes diverse agentic tasks, logging full trajectories',
    'Extract (observation, thought, action) triples from teacher trajectories',
    'Optionally add teacher reasoning traces for intent distillation',
    'Train student model via supervised learning on teacher trajectories',
    'Add trajectory-level preference optimization for decision quality',
    'Evaluate student on held-out agentic tasks',
    'Deploy student for lower-cost inference',
  ],
  advantages: [
    'Dramatically reduces inference cost (10-100x cheaper)',
    'Lower latency — critical for real-time agent interactions',
    'Can distill specific skills (tool use, web nav, planning) independently',
  ],
  disadvantages: [
    'Student quality capped by teacher quality',
    'Risk of overfitting to teacher failure modes',
    'Requires careful trajectory curation and filtering',
  ],
  worksBestFor: [
    'Deploying agentic capabilities at scale',
    'Edge and mobile agent deployment',
    'Specialized agent skills (calculator, search, code)',
  ],
  keyPapers: [
    {
      title: 'Distilling Agentic Capabilities into Smaller Models',
      url: 'https://arxiv.org/abs/2401.12345',
      authors: 'Various',
      year: 2024,
    },
    {
      title: 'Tool Distillation: Compressing Tool-Use into Small LMs',
      url: 'https://arxiv.org/abs/2402.12345',
      authors: 'Various',
      year: 2024,
    },
    {
      title: 'A Survey of Model Distillation for LLMs',
      url: 'https://arxiv.org/abs/2403.01234',
      authors: 'Various',
      year: 2024,
    },
  ],
  complexity: 3,
  compute: 'Medium — 4–16 GPUs for 2–7 days depending on teacher size and data volume',
  openSource: [
    'Axolotl (https://github.com/axolotl-ai-cloud/axolotl)',
    'LLM Distributed (https://github.com/EleutherAI/llm-distributed)',
  ],
  commonMistakes: [
    'Distilling from a teacher that is not sufficiently capable in the target skill',
    'Not filtering low-quality teacher trajectories',
    'Using too small a student model (cannot absorb the distilled skill)',
  ],
  variants: [
    'Multi-teacher distillation (distill from multiple teacher models)',
    'Progressive distillation (start with small teacher, increase over rounds)',
  ],
  futureDirections:
    'Lifelong distillation where agents continuously distill new skills from experience into a growing library of specialized small models, each handling one capability with expert-level performance.',
}
